export default {
  variable: 'Inter',
  InterThin: 'InterThin',
  InterExtraLight: 'InterExtraLight',
  InterLight: 'InterLight',
  InterRegular: 'InterRegular',
  InterMedium: 'InterMedium',
  InterSemiBold: 'InterSemiBold',
  InterBold: 'InterBold',
  InterExtraBold: 'InterExtraBold',
  light: 'SFLight',
  regular: 'SFRegular',
  medium: 'SFMedium',
  semiBold: 'SFSemiBold',
  bold: 'SFBold',
  extraBold: 'InterExtraBold',
  black: 'SFBlack',
  SFLight: 'SFLight',
  SFRegular: 'SFRegular',
  SFMedium: 'SFMedium',
  SFSemiBold: 'SFSemiBold',
  SFBold: 'SFBold',
  SFBlack: 'SFBlack',
};
